//#Gramática PEG del lenguaje delta

comment = r'[/][/].*|[/][*](.|\n)*?[*][/]'

program = expression EOF
expression = multiplicative (('+' / '-') multiplicative)* 
multiplicative = unary (('*' / '/' / '%') unary)*
unary = ('+' / '-' / '!')* primary
primary = decimal / boolean / binary / octal / hex / parenthesis
decimal = r'\d+'
boolean = 'true' / 'false'

//#Gramatica de ejercicio A
binary = r'(#b[0-1]+)'
octal = r'(#o[0-7]+)'
hex = r'(#x[a-fA-F0-9]+)'

parenthesis = '(' expression ')'
