//#Gramática PEG del lenguaje delta

comment = r'[/][/].*|[/][*](.|\n)*?[*][/]'

identifier = r'[a-zA-Z]\w*'

program = statement* expression EOF

statement = declaration / assignment / if
declaration = 'var' decl_variable (',' decl_variable)* ';'
decl_variable = identifier

assignment = lhs_variable '=' expression ';'
lhs_variable = identifier

if = 'if' expression block ('else' block)? 
block = '{' statement* '}'

expression = additive (comp_op additive)*
additive = multiplicative (('+' / '-') multiplicative)* 
multiplicative = unary (('*' / '/' / '%') unary)*
unary = ('+' / '-' / '!')* primary
primary = decimal / boolean / binary / octal / hex / parenthesis / rhs_variable
decimal = r'\d+'
boolean = 'true' / 'false'

//#Gramatica de ejercicio A
binary = r'(#b[0-1]+)'
octal = r'(#o[0-7]+)'
hex = r'(#x[a-fA-F0-9]+)'

parenthesis = '(' expression ')'
rhs_variable = identifier


//#Gramatica de ejercicio B 
comp_op = ('<=' / '>=' / '==' / '<' / '>' / '!=')
