;; Code generated by the Delta compiler
(module
  (func
    (export "_start")
    (result i32)
    (local $t i32
)    (local $u i32
)    i32.const 0
    local.set $t
    i32.const 1
    local.set $u
    local.get $u
    i32.eqz
    if (result i32)
    i32.const 1
    else
    local.get $t
    if (result i32)
    i32.const 1
    else
    local.get $u
    local.get $t
    i32.div_s
    i32.eqz
    i32.eqz
    end
    end
  )
)
