;; Code generated by the Delta compiler
(module
  (func
    (export "_start")
    (result i32)
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 0
    i32.const 2
    i32.sub
    i32.sub
    i32.sub
    i32.sub
    i32.sub
    i32.eqz
    i32.const 3
    i32.add
  )
)
